import Link from "next/link";

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100vh", background: "transparent", padding: "48px 24px", color: "var(--hw-text)" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <div style={{ marginBottom: 24 }}>
          <Link href="/" style={{ fontFamily: "var(--hw-font-mono)", fontSize: 11, letterSpacing: 4, textTransform: "uppercase" as const, color: "var(--hw-blue)", textDecoration: "none" }}>{"\u2190"} Back</Link>
        </div>
        <div style={{ fontFamily: "var(--hw-font-display)", fontSize: 40, letterSpacing: 3, textTransform: "uppercase" as const, marginBottom: 4, color: "var(--hw-text)" }}>LOCALIZER</div>
        <div style={{ width: 120, height: 3, background: "var(--hw-crimson)", marginBottom: 24 }} />
        <h1 style={{ fontFamily: "var(--hw-font-display)", fontSize: 28, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginBottom: 8, color: "var(--hw-text)" }}>Terms of Service</h1>
        <p style={{ fontFamily: "var(--hw-font-mono)", fontSize: 11, letterSpacing: 4, textTransform: "uppercase" as const, color: "var(--hw-blue)", marginBottom: 32 }}>Effective Date: June 1, 2026</p>
        <div style={{ background: "var(--hw-bg-surface)", borderRadius: 0, border: "3px solid var(--hw-border-strong)", padding: "32px 28px", fontFamily: "var(--hw-font-body)", fontSize: 14, fontWeight: 300, lineHeight: 1.7, color: "var(--hw-text-secondary)" }}>

          <p>These Terms of Service govern your access to and use of Localizer, TourRouter, and DIY — a suite of touring industry tools operated by HWY61 LLC. By accessing or using the Service at hwy61labs.com and its subdomains (localizer.hwy61labs.com, tourrouter.hwy61labs.com, diy.hwy61labs.com), you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>1. Definitions</h2>
          <p><strong>Account</strong> means the user account you create to access the Service. <strong>Content</strong> means any images, fonts, text, tour data, or other materials you upload, create, or generate through the Service. <strong>Organization</strong> means the workspace associated with your Account. <strong>Venue Link</strong> means the unique shareable URL generated for each event. <strong>Rendered Assets</strong> means the finished poster images generated by the Service.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>2. Eligibility and Account Registration</h2>
          <p>You must be at least 18 years old to use the Service. You are responsible for maintaining the security of your Account credentials and for all activity under your Account. We reserve the right to refuse or revoke access at any time.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>3. Use of the Service</h2>
          <p>You may use the Service to import tour schedules, upload base images and fonts, configure text overlays, generate marketing assets, and distribute those assets to venues via Venue Links.</p>
          <p>You agree not to: (a) Upload content that is unlawful, defamatory, or infringing. (b) Send unsolicited communications or spam. (c) Reverse-engineer or extract source code. (d) Interfere with the Service. (e) Use automated means except through our APIs. (f) Share Account credentials. (g) Violate applicable law.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>4. Your Content</h2>
          <p>You retain all ownership rights in your Content. By uploading Content, you grant us a limited, non-exclusive, worldwide license to host, store, process, and display your Content solely for providing the Service. You are solely responsible for ensuring your Content does not infringe third-party rights. If you upload custom fonts, you represent you hold a valid license for digital marketing use.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>5. AI-Powered Features</h2>
          <p>The Service uses artificial intelligence (provided by Anthropic) to parse uploaded tour schedules, process documents (deal memos, settlements, advance responses), assist with tour routing, and automate advance communications. AI outputs may contain errors. You are responsible for reviewing all parsed data before generating assets or taking action on AI-processed information. We do not use your Content to train AI models.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>6. Venue Links and Distribution</h2>
          <p>Venue Links are publicly accessible URLs. Anyone with the link can view and download the associated Rendered Assets. You are responsible for controlling distribution. We are not responsible for downstream use after download.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>7. Subscription and Billing</h2>
          <p>The Service is offered on a subscription basis. Pricing and feature limits are on our pricing page. We reserve the right to change pricing with 30 days notice. Payments are processed through Stripe. All fees are non-refundable except as required by law. You may cancel at any time through the Account page; cancellation takes effect at the end of your billing period.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>8. Intellectual Property</h2>
          <p>The Service is owned by HWY61 LLC and protected by copyright and intellectual property laws. Localizer and HWY61 are trademarks of HWY61 LLC.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>9. Privacy</h2>
          <p>Your use of the Service is also governed by our <a href="/privacy" style={{ color: "var(--hw-crimson)", fontWeight: 700 }}>Privacy Policy</a>.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>10. Third-Party Services</h2>
          <p>The Service integrates with Supabase, Cloudinary, Stripe, Resend, Anthropic, Vercel, Mapbox (geocoding and directions), and PostHog (product analytics). Your use of these services is subject to their respective terms. We are not responsible for third-party providers.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>11. Disclaimer of Warranties</h2>
          <p style={{ fontWeight: 700 }}>THE SERVICE IS PROVIDED AS IS AND AS AVAILABLE WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>12. Limitation of Liability</h2>
          <p style={{ fontWeight: 700 }}>TO THE MAXIMUM EXTENT PERMITTED BY LAW, HWY61 LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>13. Indemnification</h2>
          <p>You agree to indemnify and hold harmless HWY61 LLC from any claims arising from: (a) your use of the Service; (b) your Content; (c) your violation of these Terms; or (d) your violation of third-party rights.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>14. DMCA and Copyright Complaints</h2>
          <p>If you believe content on the Service infringes your copyright, contact our DMCA agent at dmca@hwy61labs.com with: (a) identification of the copyrighted work; (b) location of the infringing material; (c) your contact information; (d) a good faith statement; and (e) a statement under penalty of perjury.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>15. Termination</h2>
          <p>We may suspend or terminate your Account at any time. Upon termination, we may delete your Content within 30 days.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>16. General Provisions</h2>
          <p>These Terms are governed by the laws of the State of Michigan. Any disputes shall be resolved in state or federal courts located in Michigan. These Terms constitute the entire agreement between you and HWY61 LLC.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>17. Changes to These Terms</h2>
          <p>We may update these Terms from time to time. Continued use after changes constitutes acceptance.</p>

          <div style={{ marginTop: 32, paddingTop: 20, borderTop: "1px solid var(--hw-border)", fontFamily: "var(--hw-font-mono)", fontSize: 11, letterSpacing: 2, color: "var(--hw-text-muted)" }}>
            Questions? Contact us at support@hwy61labs.com
          </div>
        </div>
      </div>
    </main>
  );
}
