import Link from "next/link";

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100vh", background: "#EEEEEE", padding: "48px 24px", color: "#111" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <div style={{ marginBottom: 24 }}>
          <Link href="/" style={{ fontSize: 13, fontWeight: 700, color: "#888", textDecoration: "none" }}>\u2190 Back</Link>
        </div>
        <div className="brand-title" style={{ fontSize: 40, marginBottom: 4 }}>LOCALIZER</div>
        <div style={{ width: 120, height: 2, background: "#111", marginBottom: 24 }} />
        <h1 style={{ fontSize: 28, fontWeight: 900, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: "#888", marginBottom: 32 }}>Effective Date: March 2026</p>
        <div style={{ background: "#fff", borderRadius: 14, border: "1px solid #ddd", padding: "32px 28px", fontSize: 14, lineHeight: 1.7 }}>

          <p>These Terms of Service govern your access to and use of Localizer, a tour marketing asset management platform operated by HWY61 AI. By accessing or using Localizer at localizer.hwy61labs.com or any related services, you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>1. Definitions</h2>
          <p><strong>Account</strong> means the user account you create to access the Service. <strong>Content</strong> means any images, fonts, text, tour data, or other materials you upload, create, or generate through the Service. <strong>Organization</strong> means the workspace associated with your Account. <strong>Venue Link</strong> means the unique shareable URL generated for each event. <strong>Rendered Assets</strong> means the finished poster images generated by the Service.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>2. Eligibility and Account Registration</h2>
          <p>You must be at least 18 years old to use the Service. You are responsible for maintaining the security of your Account credentials and for all activity under your Account. Account creation is currently by invitation only. We reserve the right to refuse or revoke access at any time.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>3. Use of the Service</h2>
          <p>You may use the Service to import tour schedules, upload base images and fonts, configure text overlays, generate marketing assets, and distribute those assets to venues via Venue Links.</p>
          <p>You agree not to: (a) Upload content that is unlawful, defamatory, or infringing. (b) Send unsolicited communications or spam. (c) Reverse-engineer or extract source code. (d) Interfere with the Service. (e) Use automated means except through our APIs. (f) Share Account credentials. (g) Violate applicable law.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>4. Your Content</h2>
          <p>You retain all ownership rights in your Content. By uploading Content, you grant us a limited, non-exclusive, worldwide license to host, store, process, and display your Content solely for providing the Service. You are solely responsible for ensuring your Content does not infringe third-party rights. If you upload custom fonts, you represent you hold a valid license for digital marketing use.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>5. AI-Powered Features</h2>
          <p>The Service uses artificial intelligence (provided by Anthropic) to parse uploaded tour schedules. AI outputs may contain errors. You are responsible for reviewing all parsed data before generating assets. We do not use your Content to train AI models.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>6. Venue Links and Distribution</h2>
          <p>Venue Links are publicly accessible URLs. Anyone with the link can view and download the associated Rendered Assets. You are responsible for controlling distribution. We are not responsible for downstream use after download.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>7. Subscription and Billing</h2>
          <p>The Service is offered on a subscription basis. Pricing and feature limits are on our pricing page. We reserve the right to change pricing with 30 days notice. Payments are processed through Stripe. All fees are non-refundable except as required by law. You may cancel at any time through the Account page; cancellation takes effect at the end of your billing period. Each plan includes a monthly render limit.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>8. Intellectual Property</h2>
          <p>The Service is owned by HWY61 AI and protected by copyright and intellectual property laws. Localizer and HWY61 are trademarks of HWY61 AI.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>9. Privacy</h2>
          <p>Your use of the Service is also governed by our <a href="/privacy" style={{ color: "#111", fontWeight: 700 }}>Privacy Policy</a>.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>10. Third-Party Services</h2>
          <p>The Service integrates with Supabase, Cloudinary, Stripe, Resend, Anthropic, and Vercel. Your use of these services is subject to their respective terms. We are not responsible for third-party providers.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>11. Disclaimer of Warranties</h2>
          <p style={{ fontWeight: 700 }}>THE SERVICE IS PROVIDED AS IS AND AS AVAILABLE WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>12. Limitation of Liability</h2>
          <p style={{ fontWeight: 700 }}>TO THE MAXIMUM EXTENT PERMITTED BY LAW, HWY61 AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>13. Indemnification</h2>
          <p>You agree to indemnify and hold harmless HWY61 AI from any claims arising from: (a) your use of the Service; (b) your Content; (c) your violation of these Terms; or (d) your violation of third-party rights.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>14. DMCA and Copyright Complaints</h2>
          <p>If you believe content on the Service infringes your copyright, contact our DMCA agent at dmca@hwy61labs.com with: (a) identification of the copyrighted work; (b) location of the infringing material; (c) your contact information; (d) a good faith statement; and (e) a statement under penalty of perjury.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>15. Termination</h2>
          <p>We may suspend or terminate your Account at any time. Upon termination, we may delete your Content within 30 days.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>16. General Provisions</h2>
          <p>These Terms are governed by the laws of the State of Michigan. Any disputes shall be resolved in state or federal courts located in Michigan. These Terms constitute the entire agreement between you and HWY61 AI.</p>

          <h2 style={{ fontSize: 18, fontWeight: 900, marginTop: 32, marginBottom: 12 }}>17. Changes to These Terms</h2>
          <p>We may update these Terms from time to time. Continued use after changes constitutes acceptance.</p>

          <div style={{ marginTop: 32, paddingTop: 20, borderTop: "1px solid #eee", fontSize: 13, color: "#888" }}>
            Questions? Contact us at support@hwy61labs.com
          </div>
        </div>
      </div>
    </main>
  );
}
