import Link from "next/link";

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100vh", background: "transparent", padding: "48px 24px", color: "var(--hw-text)" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <div style={{ marginBottom: 24 }}>
          <Link href="/" style={{ fontFamily: "var(--hw-font-mono)", fontSize: 11, letterSpacing: 4, textTransform: "uppercase" as const, color: "var(--hw-blue)", textDecoration: "none" }}>{"\u2190"} Back</Link>
        </div>
        <div style={{ fontFamily: "var(--hw-font-display)", fontSize: 40, letterSpacing: 3, textTransform: "uppercase" as const, marginBottom: 4, color: "var(--hw-text)" }}>LOCALIZER</div>
        <div style={{ width: 120, height: 3, background: "var(--hw-crimson)", marginBottom: 24 }} />
        <h1 style={{ fontFamily: "var(--hw-font-display)", fontSize: 28, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginBottom: 8, color: "var(--hw-text)" }}>Terms of Service</h1>
        <p style={{ fontFamily: "var(--hw-font-mono)", fontSize: 11, letterSpacing: 4, textTransform: "uppercase" as const, color: "var(--hw-blue)", marginBottom: 4 }}>Effective Date: [SET AT PUBLISH]</p>
        <p style={{ fontFamily: "var(--hw-font-mono)", fontSize: 11, letterSpacing: 4, textTransform: "uppercase" as const, color: "var(--hw-blue)", marginBottom: 32 }}>Last Updated: July 6, 2026</p>
        <div style={{ background: "var(--hw-bg-surface)", borderRadius: 0, border: "3px solid var(--hw-border-strong)", padding: "32px 28px", fontFamily: "var(--hw-font-body)", fontSize: 14, fontWeight: 300, lineHeight: 1.7, color: "var(--hw-text-secondary)" }}>

          <p>These Terms of Service govern your access to and use of Localizer, a tour marketing asset platform operated by HWY61 LLC. By accessing or using the Service at hwy61labs.com, you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>1. Definitions</h2>
          <p><strong>Account</strong> means the user account you create to access the Service. <strong>Content</strong> means any images, fonts, text, tour data, or other materials you upload, create, or generate through the Service. <strong>Organization</strong> means the workspace associated with your Account. <strong>Venue Link</strong> means the unique shareable URL generated for each event. <strong>Rendered Assets</strong> means the finished poster images generated by the Service.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>2. Eligibility and Account Registration</h2>
          <p>You must be at least 18 years old to use the Service. You are responsible for maintaining the security of your Account credentials and for all activity under your Account. We reserve the right to refuse, suspend, or revoke access at any time.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>3. Use of the Service</h2>
          <p>You may use the Service to import tour schedules, upload base images and fonts, configure text overlays, generate marketing assets, and distribute those assets to venues via Venue Links.</p>
          <p>You agree not to: (a) Upload content that is unlawful, defamatory, or infringing. (b) Send unsolicited communications or spam. (c) Reverse-engineer or extract source code. (d) Interfere with the Service. (e) Use automated means except through our APIs. (f) Share Account credentials. (g) Violate applicable law.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>4. Your Content</h2>
          <p>You retain all ownership rights in your Content. By uploading Content, you grant us a limited, non-exclusive, worldwide license to host, store, process, and display your Content solely for providing the Service. You represent and warrant that you own or hold valid licenses for all Content you upload — including photographic images, artwork, logos, trademarks, and fonts — and you are solely responsible for ensuring your Content does not infringe third-party rights. If you upload custom fonts, you represent you hold a valid license for digital marketing use; we do not verify font licenses.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>5. AI-Powered Features</h2>
          <p>The Service uses artificial intelligence (provided by Anthropic) to parse uploaded tour schedules and extract structured data such as dates, venues, cities, and contact information. AI outputs may contain errors. You are responsible for reviewing and verifying all parsed data before generating assets. We do not use your Content to train AI models.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>6. Venue Links and Distribution</h2>
          <p>Venue Links are publicly accessible URLs: anyone with the link can view the page and download the materials you include on it, which may include Rendered Assets, team contact information, advance and technical documents, and tax documents such as a W-9. Visibility settings let you control whether team contacts, advance documents, and tax documents appear on each Venue Link. By adding contact information for any individual — including members of your team — to a Venue Link, you represent that you have that person's consent or other authority to share it with recipients of the link. You are responsible for controlling distribution of your Venue Links. We are not responsible for downstream use of materials after download.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>7. Free Trial, Subscription, and Billing</h2>
          <p>We may offer a free trial of the Service. No payment method is required to begin a trial. At the end of the trial period, access to paid features will be limited unless you select a paid plan. After any trial, the Service is offered on a subscription basis; current plans, pricing, and feature limits are on our pricing page. We reserve the right to change pricing with 30 days notice to existing subscribers. When you subscribe, payments are processed through Stripe and you authorize us to charge your payment method on a recurring basis until you cancel. All fees are non-refundable except as required by law. You may cancel at any time through the Account page or Stripe Customer Portal; cancellation takes effect at the end of your current billing period.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>8. Intellectual Property</h2>
          <p>The Service is owned by HWY61 LLC and protected by copyright and intellectual property laws. Localizer and HWY61 are trademarks of HWY61 LLC.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>9. Privacy</h2>
          <p>Your use of the Service is also governed by our <a href="/privacy" style={{ color: "var(--hw-crimson)", fontWeight: 700 }}>Privacy Policy</a>.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>10. Third-Party Services</h2>
          <p>The Service integrates with Supabase, Cloudinary, Stripe, Resend, Anthropic, PostHog, Vercel, and Upstash. Your use of these services is subject to their respective terms and privacy policies. We are not responsible for the acts or omissions of third-party providers.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>11. Disclaimer of Warranties</h2>
          <p style={{ fontWeight: 700 }}>THE SERVICE IS PROVIDED AS IS AND AS AVAILABLE WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>12. Limitation of Liability</h2>
          <p style={{ fontWeight: 700 }}>TO THE MAXIMUM EXTENT PERMITTED BY LAW, HWY61 LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR TOTAL LIABILITY SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS PRECEDING THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS ($100).</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>13. Indemnification</h2>
          <p>You agree to indemnify and hold harmless HWY61 LLC from any claims arising from: (a) your use of the Service; (b) your Content; (c) your violation of these Terms; or (d) your violation of third-party rights.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>14. DMCA and Copyright Complaints</h2>
          <p>We respect the intellectual property rights of others and maintain a registered DMCA agent. If you believe content on the Service infringes your copyright, send a notice to dmca@hwy61labs.com including: (a) identification of the copyrighted work; (b) location of the infringing material; (c) your contact information; (d) a good faith statement; and (e) a statement under penalty of perjury that the information is accurate and you are authorized to act for the copyright owner.</p>
          <p><strong>Counter-Notices.</strong> If your content was removed in response to a copyright notice and you believe the removal was a mistake or misidentification, you may send a counter-notice to dmca@hwy61labs.com including: (a) identification of the material removed and the location where it appeared before removal; (b) a statement under penalty of perjury that you have a good-faith belief the material was removed as a result of mistake or misidentification; (c) your name, address, and telephone number; (d) a statement that you consent to the jurisdiction of the federal district court for the judicial district in which your address is located (or, if you are outside the United States, the federal courts located in Texas) and that you will accept service of process from the person who submitted the original notice; and (e) your physical or electronic signature. Unless the original claimant notifies us that they have filed a court action seeking to restrain the alleged infringement, we may restore the removed material no sooner than 10 and no later than 14 business days after receiving a valid counter-notice.</p>
          <p><strong>Repeat Infringers.</strong> We will terminate the accounts of users who are repeat infringers in appropriate circumstances.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>15. Termination</h2>
          <p>We may suspend or terminate your Account at any time, including for violation of these Terms. Upon termination, your right to use the Service ceases immediately, and we may delete your Content within 30 days. Sections that by their nature should survive (including 4, 8, 11, 12, 13, and 16) will survive.</p>

          <h2 style={{ fontFamily: "var(--hw-font-display)", fontSize: 18, fontWeight: 400, letterSpacing: 2, textTransform: "uppercase" as const, marginTop: 32, marginBottom: 12, color: "var(--hw-text)" }}>16. General Provisions</h2>
          <p>These Terms constitute the entire agreement between you and HWY61 LLC regarding the Service. If any provision is found unenforceable, the rest continue in effect. These Terms are governed by the laws of the State of Texas without regard to its conflict of laws provisions. Any disputes shall be resolved in the state or federal courts located in Texas. We may update these Terms from time to time and will notify you of material changes; continued use after changes constitutes acceptance. Questions: support@hwy61labs.com.</p>

        </div>
      </div>
    </main>
  );
}
